### PR TITLE
Renamings

### LINKED ISSUE #230: Rename PaymentProcessor contracts
For clarity:
PaymentProcessor (the contract, but not the interface!) -> SimplePaymentProcessor
VestingPaymentProcessor -> StreamingPaymentProcessor

### PR DESCRIPTION
**Pull request by 0xNuggan**
closes #230 and #232

Draft for now, will need review after merging #226 

Also, see comment on #232

### CODE REVIEW

**Review by marvinkruse — COMMENTED** [review]
Looks good otherwise, just two comments + 1 question

**Review by marvinkruse — APPROVED** [review]
lgtm! nice one

**Review by FHieser — COMMENTED** [review]
VestingPaymentProcessor.t.sol has to be renamed to StreamingPaymentProcessor.t.sol

**Review by FHieser — COMMENTED** [review]
VestingPaymentProcessor.t.sol has to be renamed to StreamingPaymentProcessor.t.sol

**Review by FHieser — COMMENTED** [review]
VestingPaymentProcessor.t.sol has to be renamed to StreamingPaymentProcessor.t.sol

**Review by FHieser — COMMENTED** [review]
VestingPaymentProcessor.t.sol has to be renamed to StreamingPaymentProcessor.t.sol

**Review by FHieser — COMMENTED** [review]
VestingPaymentProcessor.t.sol has to be renamed to StreamingPaymentProcessor.t.sol

Edit: I had problems with the internet connection during the review, thats why this comment is her 5 times xD

**Pull request merged**
